version: "3.9"
services:
  web:
    image: registry.gitlab.utc.fr/multeract/server
    ports:
      - "30000:8080"
    networks:
      - backend
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: isThisSecret?
      MYSQL_DATABASE: server
      MYSQL_USER: root
      MYSQL_PASSWORD: isThisSecret?
    ports:
      - "3306"
    networks:
      - backend
    volumes:
      - ./data:/var/lib/mysql

networks:
  backend:
    driver: bridge